# Generated by Django 5.2.1 on 2025-05-24 12:45

import django.utils.timezone
import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('education_summary', models.TextField(blank=True, null=True)),
                ('experience_summary', models.TextField(blank=True, null=True)),
                ('skills_summary', models.TextField(blank=True, null=True)),
                ('original_file', models.FileField(upload_to=resumes.models.resume_upload_path)),
                ('full_text_content', models.TextField(blank=True, help_text='Conteúdo completo extraído do arquivo original.', null=True)),
                ('source', models.CharField(choices=[('email', 'E-mail'), ('physical', 'Físico (Digitalizado)'), ('manual', 'Cadastro Manual'), ('other', 'Outro')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('pending_review', 'Pendente de Revisão'), ('under_review', 'Em Revisão'), ('shortlisted', 'Pré-selecionado'), ('interview_scheduled', 'Entevista Agendada'), ('rejected', 'Rejeitado'), ('hired', 'Contratado')], default='pending_review', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Anotações internas sobre o candidato.', null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculo',
                'verbose_name_plural': 'Curriculos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
